/****************************************************************************
**
** Metadata for OphirLMMeasurementLib generated by dumpcpp v5.6.3 using
** dumpcpp.exe C:\OphirLMMeasurement.dll
** from the type library C:\OphirLMMeasurement.dll
**
****************************************************************************/

#define QAX_DUMPCPP_OPHIRLMMEASUREMENTLIB_NOINLINES
#include "ophirlmmeasurement.h"

using namespace OphirLMMeasurementLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[99];
    char stringdata0[1226];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 38, 0),
QT_MOC_LITERAL(1, 39, 17, 0),
QT_MOC_LITERAL(2, 57, 23, 0),
QT_MOC_LITERAL(3, 81, 11, 0),
QT_MOC_LITERAL(4, 93, 16, 0),
QT_MOC_LITERAL(5, 110, 9, 0),
QT_MOC_LITERAL(6, 120, 0, 0),
QT_MOC_LITERAL(7, 121, 7, 0),
QT_MOC_LITERAL(8, 129, 7, 0),
QT_MOC_LITERAL(9, 137, 11, 0),
QT_MOC_LITERAL(10, 149, 9, 0),
QT_MOC_LITERAL(11, 159, 4, 0),
QT_MOC_LITERAL(12, 164, 6, 0),
QT_MOC_LITERAL(13, 171, 4, 0),
QT_MOC_LITERAL(14, 176, 4, 0),
QT_MOC_LITERAL(15, 181, 15, 0),
QT_MOC_LITERAL(16, 197, 4, 0),
QT_MOC_LITERAL(17, 202, 6, 0),
QT_MOC_LITERAL(18, 209, 4, 0),
QT_MOC_LITERAL(19, 214, 4, 0),
QT_MOC_LITERAL(20, 219, 13, 0),
QT_MOC_LITERAL(21, 233, 10, 0),
QT_MOC_LITERAL(22, 244, 5, 0),
QT_MOC_LITERAL(23, 250, 8, 0),
QT_MOC_LITERAL(24, 259, 19, 0),
QT_MOC_LITERAL(25, 279, 4, 0),
QT_MOC_LITERAL(26, 284, 6, 0),
QT_MOC_LITERAL(27, 291, 16, 0),
QT_MOC_LITERAL(28, 308, 5, 0),
QT_MOC_LITERAL(29, 314, 7, 0),
QT_MOC_LITERAL(30, 322, 9, 0),
QT_MOC_LITERAL(31, 332, 10, 0),
QT_MOC_LITERAL(32, 343, 14, 0),
QT_MOC_LITERAL(33, 358, 11, 0),
QT_MOC_LITERAL(34, 370, 13, 0),
QT_MOC_LITERAL(35, 384, 8, 0),
QT_MOC_LITERAL(36, 393, 10, 0),
QT_MOC_LITERAL(37, 404, 10, 0),
QT_MOC_LITERAL(38, 415, 12, 0),
QT_MOC_LITERAL(39, 428, 11, 0),
QT_MOC_LITERAL(40, 440, 4, 0),
QT_MOC_LITERAL(41, 445, 7, 0),
QT_MOC_LITERAL(42, 453, 16, 0),
QT_MOC_LITERAL(43, 470, 4, 0),
QT_MOC_LITERAL(44, 475, 16, 0),
QT_MOC_LITERAL(45, 492, 9, 0),
QT_MOC_LITERAL(46, 502, 11, 0),
QT_MOC_LITERAL(47, 514, 15, 0),
QT_MOC_LITERAL(48, 530, 15, 0),
QT_MOC_LITERAL(49, 546, 20, 0),
QT_MOC_LITERAL(50, 567, 13, 0),
QT_MOC_LITERAL(51, 581, 9, 0),
QT_MOC_LITERAL(52, 591, 23, 0),
QT_MOC_LITERAL(53, 615, 13, 0),
QT_MOC_LITERAL(54, 629, 18, 0),
QT_MOC_LITERAL(55, 648, 15, 0),
QT_MOC_LITERAL(56, 664, 9, 0),
QT_MOC_LITERAL(57, 674, 13, 0),
QT_MOC_LITERAL(58, 688, 8, 0),
QT_MOC_LITERAL(59, 697, 8, 0),
QT_MOC_LITERAL(60, 706, 12, 0),
QT_MOC_LITERAL(61, 719, 10, 0),
QT_MOC_LITERAL(62, 730, 7, 0),
QT_MOC_LITERAL(63, 738, 14, 0),
QT_MOC_LITERAL(64, 753, 19, 0),
QT_MOC_LITERAL(65, 773, 5, 0),
QT_MOC_LITERAL(66, 779, 10, 0),
QT_MOC_LITERAL(67, 790, 13, 0),
QT_MOC_LITERAL(68, 804, 13, 0),
QT_MOC_LITERAL(69, 818, 14, 0),
QT_MOC_LITERAL(70, 833, 6, 0),
QT_MOC_LITERAL(71, 840, 16, 0),
QT_MOC_LITERAL(72, 857, 13, 0),
QT_MOC_LITERAL(73, 871, 18, 0),
QT_MOC_LITERAL(74, 890, 4, 0),
QT_MOC_LITERAL(75, 895, 5, 0),
QT_MOC_LITERAL(76, 901, 15, 0),
QT_MOC_LITERAL(77, 917, 11, 0),
QT_MOC_LITERAL(78, 929, 12, 0),
QT_MOC_LITERAL(79, 942, 7, 0),
QT_MOC_LITERAL(80, 950, 12, 0),
QT_MOC_LITERAL(81, 963, 11, 0),
QT_MOC_LITERAL(82, 975, 14, 0),
QT_MOC_LITERAL(83, 990, 15, 0),
QT_MOC_LITERAL(84, 1006, 20, 0),
QT_MOC_LITERAL(85, 1027, 17, 0),
QT_MOC_LITERAL(86, 1045, 9, 0),
QT_MOC_LITERAL(87, 1055, 18, 0),
QT_MOC_LITERAL(88, 1074, 14, 0),
QT_MOC_LITERAL(89, 1089, 8, 0),
QT_MOC_LITERAL(90, 1098, 12, 0),
QT_MOC_LITERAL(91, 1111, 13, 0),
QT_MOC_LITERAL(92, 1125, 11, 0),
QT_MOC_LITERAL(93, 1137, 14, 0),
QT_MOC_LITERAL(94, 1152, 10, 0),
QT_MOC_LITERAL(95, 1163, 5, 0),
QT_MOC_LITERAL(96, 1169, 7, 0),
QT_MOC_LITERAL(97, 1177, 39, 0),
QT_MOC_LITERAL(98, 1217, 7, 0)
    },
    "OphirLMMeasurementLib::CoLMMeasurement\0Event Interface 1\0_ICoLMMeasurementEvents\0"
    "Interface 0\0ICoLMMeasurement\0DataReady\0\0hDevice\0channel\0PlugAndPlay\0exception\0"
    "code\0source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0AddWavelength\0"
    "wavelength\0Close\0CloseAll\0ConfigureStreamMode\0mode\0nValue\0DeleteWavelength\0"
    "index\0GetData\0QVariant&\0arrayValue\0arrayTimestamp\0arrayStatus\0GetDeviceInfo\0"
    "QString&\0deviceName\0romVersion\0serialNumber\0GetDiffuser\0int&\0options\0"
    "GetDriverVersion\0info\0GetErrorFromCode\0errorCode\0errorString\0GetExtTrigModes\0"
    "GetExtTrigOnOff\0GetExtTrigWindowTime\0extTrigWindow\0GetFilter\0GetKnownWirelessDevices\0"
    "serialNumbers\0GetMeasurementMode\0GetPulseLengths\0GetRanges\0GetSensorInfo\0"
    "headType\0headName\0GetThreshold\0GetVersion\0version\0GetWavelengths\0GetWavelengthsExtra\0"
    "bool&\0modifiable\0minWavelength\0maxWavelength\0IsSensorExists\0exists\0"
    "ModifyWavelength\0OpenUSBDevice\0OpenWirelessDevice\0Read\0reply\0ResetAllDevices\0"
    "ResetDevice\0SaveSettings\0ScanUSB\0ScanWireless\0SetDiffuser\0SetExtTrigMode\0"
    "SetExtTrigOnOff\0SetExtTrigWindowTime\0extTrigWindowTime\0SetFilter\0SetMeasurementMode\0"
    "SetPulseLength\0SetRange\0SetThreshold\0SetWavelength\0StartStream\0StopAllStreams\0"
    "StopStream\0Write\0command\0OphirLMMeasurementLib::ICoLMMeasurement\0control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_OphirLMMeasurementLib__CoLMMeasurement[] = {

 // content:
    7, // revision
    0,  // classname
    2, 14, // classinfo
    52, 18, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    5, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 

// signal: name, argc, parameters, tag, flags
    5, 2, 278, 6, 5,
    9, 0, 283, 6, 5,
    10, 4, 284, 6, 5,
    15, 1, 293, 6, 5,
    17, 3, 296, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 3, 303, 6, 9,
    22, 1, 310, 6, 9,
    23, 0, 313, 6, 9,
    24, 4, 314, 6, 9,
    27, 3, 323, 6, 9,
    29, 5, 330, 6, 9,
    34, 4, 341, 6, 9,
    39, 4, 350, 6, 9,
    42, 1, 359, 6, 9,
    44, 2, 362, 6, 9,
    47, 3, 367, 6, 9,
    48, 4, 374, 6, 9,
    49, 2, 383, 6, 9,
    51, 4, 388, 6, 9,
    52, 1, 397, 6, 9,
    54, 4, 400, 6, 9,
    55, 4, 409, 6, 9,
    56, 4, 418, 6, 9,
    57, 5, 427, 6, 9,
    60, 4, 438, 6, 9,
    61, 1, 447, 6, 9,
    63, 4, 450, 6, 9,
    64, 5, 459, 6, 9,
    69, 3, 470, 6, 9,
    71, 4, 477, 6, 9,
    72, 2, 486, 6, 9,
    73, 2, 491, 6, 9,
    74, 2, 496, 6, 9,
    76, 0, 501, 6, 9,
    77, 1, 502, 6, 9,
    78, 2, 505, 6, 9,
    79, 1, 510, 6, 9,
    80, 1, 513, 6, 9,
    81, 3, 516, 6, 9,
    82, 2, 523, 6, 9,
    83, 3, 528, 6, 9,
    84, 2, 535, 6, 9,
    86, 3, 540, 6, 9,
    87, 3, 547, 6, 9,
    88, 3, 554, 6, 9,
    89, 3, 561, 6, 9,
    90, 3, 568, 6, 9,
    91, 3, 575, 6, 9,
    92, 2, 582, 6, 9,
    93, 0, 587, 6, 9,
    94, 2, 588, 6, 9,
    95, 2, 593, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 21,
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 25, 26,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 30, 0x80000000 | 30, 0x80000000 | 30, 7, 8, 31, 32, 33,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 35, 0x80000000 | 35, 0x80000000 | 35, 7, 36, 37, 38,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, 0x80000000 | 35, 43,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 35, 45, 46,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 40, 7, 50,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, 0x80000000 | 30, 53,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 35, 0x80000000 | 35, 0x80000000 | 35, 7, 8, 38, 58, 59,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, 0x80000000 | 40, 62,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 65, 0x80000000 | 40, 0x80000000 | 40, 7, 8, 66, 67, 68,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 65, 7, 8, 70,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28, 21,
    QMetaType::Void, QMetaType::QString, 0x80000000 | 40, 38, 7,
    QMetaType::Void, QMetaType::QString, 0x80000000 | 40, 38, 7,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 35, 7, 75,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void, 0x80000000 | 30, 53,
    QMetaType::Void, 0x80000000 | 30, 53,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 85,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 7, 96,

    0 // eod
};

const QMetaObject CoLMMeasurement::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OphirLMMeasurementLib__CoLMMeasurement, 0, 0, 0 }
};

void *CoLMMeasurement::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OphirLMMeasurementLib::CoLMMeasurement"))
        return static_cast<void*>(const_cast<CoLMMeasurement*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_OphirLMMeasurementLib__ICoLMMeasurement[] = {

 // content:
    7, // revision
    97,  // classname
    0, 0, // classinfo
    50, 14, // methods
    1, 578, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    10, 4, 264, 6, 5,
    15, 1, 273, 6, 5,
    17, 3, 276, 6, 5,

// slot: name, argc, parameters, tag, flags
    20, 3, 283, 6, 9,
    22, 1, 290, 6, 9,
    23, 0, 293, 6, 9,
    24, 4, 294, 6, 9,
    27, 3, 303, 6, 9,
    29, 5, 310, 6, 9,
    34, 4, 321, 6, 9,
    39, 4, 330, 6, 9,
    42, 1, 339, 6, 9,
    44, 2, 342, 6, 9,
    47, 3, 347, 6, 9,
    48, 4, 354, 6, 9,
    49, 2, 363, 6, 9,
    51, 4, 368, 6, 9,
    52, 1, 377, 6, 9,
    54, 4, 380, 6, 9,
    55, 4, 389, 6, 9,
    56, 4, 398, 6, 9,
    57, 5, 407, 6, 9,
    60, 4, 418, 6, 9,
    61, 1, 427, 6, 9,
    63, 4, 430, 6, 9,
    64, 5, 439, 6, 9,
    69, 3, 450, 6, 9,
    71, 4, 457, 6, 9,
    72, 2, 466, 6, 9,
    73, 2, 471, 6, 9,
    74, 2, 476, 6, 9,
    76, 0, 481, 6, 9,
    77, 1, 482, 6, 9,
    78, 2, 485, 6, 9,
    79, 1, 490, 6, 9,
    80, 1, 493, 6, 9,
    81, 3, 496, 6, 9,
    82, 2, 503, 6, 9,
    83, 3, 508, 6, 9,
    84, 2, 515, 6, 9,
    86, 3, 520, 6, 9,
    87, 3, 527, 6, 9,
    88, 3, 534, 6, 9,
    89, 3, 541, 6, 9,
    90, 3, 548, 6, 9,
    91, 3, 555, 6, 9,
    92, 2, 562, 6, 9,
    93, 0, 567, 6, 9,
    94, 2, 568, 6, 9,
    95, 2, 573, 6, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 21,
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 25, 26,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 30, 0x80000000 | 30, 0x80000000 | 30, 7, 8, 31, 32, 33,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 35, 0x80000000 | 35, 0x80000000 | 35, 7, 36, 37, 38,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, 0x80000000 | 35, 43,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 35, 45, 46,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 40, 7, 50,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, 0x80000000 | 30, 53,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 35, 0x80000000 | 35, 0x80000000 | 35, 7, 8, 38, 58, 59,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, 0x80000000 | 40, 62,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 40, 0x80000000 | 30, 7, 8, 28, 41,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 65, 0x80000000 | 40, 0x80000000 | 40, 7, 8, 66, 67, 68,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 65, 7, 8, 70,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28, 21,
    QMetaType::Void, QMetaType::QString, 0x80000000 | 40, 38, 7,
    QMetaType::Void, QMetaType::QString, 0x80000000 | 40, 38, 7,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 35, 7, 75,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 7,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void, 0x80000000 | 30, 53,
    QMetaType::Void, 0x80000000 | 30, 53,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 85,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 7, 8, 28,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 7, 8,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, 7, 96,

 // properties: name, type, flags
    98, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject ICoLMMeasurement::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_OphirLMMeasurementLib__ICoLMMeasurement, 0, 0, 0 }
};

void *ICoLMMeasurement::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "OphirLMMeasurementLib::ICoLMMeasurement"))
        return static_cast<void*>(const_cast<ICoLMMeasurement*>(this));
    return QAxObject::qt_metacast(_clname);
}

